name: Verify

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: verifies that release setup works correctly
        run: |
          export VERSION=0.0.1-ci-SNAPSHOT 
          export SOURCE_BRANCH=main 
          ./release-setup.sh
      - name: publish to maven local
        run: |
          ./gradlew -Pskip.signing=true publishToMavenLocal \
              -Dorg.gradle.internal.network.retry.max.attempts=5 -Dorg.gradle.internal.network.retry.initial.backOff=5000
