name: Verify

on:
  push:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'CODEOWNERS'
      - 'LICENSE'

jobs:
  Prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: verifies that prepare doesn't throw errors
        run: VERSION=0.0.1-ci-SNAPSHOT ./prepare.sh
      - name: publish to maven local
        run: ./gradlew -Pskip.signing=true publishToMavenLocal
